Tensor 和NumPy的多维数组非常类似。然而，Tensor 提供GPU计算和自动求梯度等更多功能，这些使 Tensor 这一数据类型更加适合深度学习。

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.rand(4, 3) 
print(x)

tensor([[0.7636, 0.4787, 0.3516],
        [0.0342, 0.3082, 0.8164],
        [0.8644, 0.4125, 0.2631],
        [0.8161, 0.6578, 0.1350]])


In [3]:
x = torch.zeros(4,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
x = torch.tensor([5.5, 3]) 
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(4,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
x = torch.randn_like(x, dtype=torch.float) # 返回和 x shpe 一样的 randn 
x

tensor([[-1.6785,  1.7626, -1.2145],
        [-0.0078, -0.2937,  0.7346],
        [ 1.9619,  0.3324,  0.3054],
        [-1.0524, -1.2322, -0.4208]])

In [8]:
# 方式1
y = torch.rand(4, 3) 
print(x + y)

# 方式2
print(torch.add(x, y))

tensor([[-0.7146,  2.6093, -1.1562],
        [ 0.6869,  0.3521,  1.0896],
        [ 2.1086,  0.4796,  0.6922],
        [-0.7284, -0.3347,  0.4829]])
tensor([[-0.7146,  2.6093, -1.1562],
        [ 0.6869,  0.3521,  1.0896],
        [ 2.1086,  0.4796,  0.6922],
        [-0.7284, -0.3347,  0.4829]])


In [9]:
# 方式3 提供一个输出 tensor 作为参数
result = torch.empty(5, 3) 
torch.add(x, y, out=result) 
print(result)

tensor([[-0.7146,  2.6093, -1.1562],
        [ 0.6869,  0.3521,  1.0896],
        [ 2.1086,  0.4796,  0.6922],
        [-0.7284, -0.3347,  0.4829]])


D:\MyData\chenpf8\AppData\Local\Temp/ipykernel_3252/453478057.py:3: UserWarning: An output with one or more elements was resized since it had shape [5, 3], which does not match the required output shape [4, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ..\aten\src\ATen\native\Resize.cpp:23.)
  torch.add(x, y, out=result)


In [10]:
result = torch.empty(5, 3) 
result

tensor([[6.2449e-39, 8.7245e-39, 6.1531e-39],
        [7.6225e-39, 5.0511e-39, 4.4082e-39],
        [7.6225e-39, 6.0612e-39, 4.8674e-39],
        [8.9081e-39, 4.5919e-39, 9.2755e-39],
        [9.0000e-39, 4.4082e-39, 4.4082e-39]])

In [11]:
# 取第二列
print(x[:, 1]) 

tensor([ 1.7626, -0.2937,  0.3324, -1.2322])


In [14]:
y = x[0,:]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了了

tensor([0.3215, 3.7626, 0.7855])
tensor([0.3215, 3.7626, 0.7855])


In [13]:
x

tensor([[-0.6785,  2.7626, -0.2145],
        [-0.0078, -0.2937,  0.7346],
        [ 1.9619,  0.3324,  0.3054],
        [-1.0524, -1.2322, -0.4208]])

In [15]:
x

tensor([[ 0.3215,  3.7626,  0.7855],
        [-0.0078, -0.2937,  0.7346],
        [ 1.9619,  0.3324,  0.3054],
        [-1.0524, -1.2322, -0.4208]])

In [16]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**注意 view() 返回的新tensor与源tensor共享内存(其实是同一个tensor)，也即更改其中的一个，另 外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察⻆度)**

In [17]:
x

tensor([[-0.1362,  1.1937, -0.2556, -1.0839],
        [ 0.1538,  0.5933,  1.6010,  1.2899],
        [ 1.2090,  1.1760, -1.1430,  0.5111],
        [-0.6114,  0.1387, -0.9569,  0.3922]])

In [18]:
x += 1
print(x)
print(y) # 也加了了1

tensor([[ 0.8638,  2.1937,  0.7444, -0.0839],
        [ 1.1538,  1.5933,  2.6010,  2.2899],
        [ 2.2090,  2.1760, -0.1430,  1.5111],
        [ 0.3886,  1.1387,  0.0431,  1.3922]])
tensor([ 0.8638,  2.1937,  0.7444, -0.0839,  1.1538,  1.5933,  2.6010,  2.2899,
         2.2090,  2.1760, -0.1430,  1.5111,  0.3886,  1.1387,  0.0431,  1.3922])


所以如果我们想返回一个真正新的副本(即不共享内存)该怎么办呢？Pytorch还提供了一 个 reshape() 可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。
**推荐先用 clone 创造一个副本然后再使用 view 。**

In [19]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


PyTorch 中，所有神经网络的核心是 autograd包。autograd包为张量上的所有操作提供了自动求导机制。

torch.Tensor是这个包的核心类。如果**设置它的属性.requires_grad 为 True，那么它将会追踪对于该张量的所有操作**。当完成计算后可以通过调用.backward()，来自动计算所有的梯度。这个张量的所有梯度将会自动累加到.grad属性。

注意：在 y.backward() 时，如果 y 是标量，则不需要为 backward() 传入任何参数；否则，需要传入一个与 y 同形的Tensor。


要阻止一个张量被跟踪历史，可以调用.detach()方法将其与计算历史分离，并阻止它未来的计算记录被跟踪。

为了防止跟踪历史记录(和使用内存），可以将代码块包装在 with torch.no_grad():中，在评估模型时特别有用，因为模型可能具有 requires_grad = True 的可训练的参数，但是我们不需要在此过程中对他们进行梯度计算。

还有一个类对于autograd的实现非常重要：Function。Tensor和Function 互相连接生成了一个无环图 (acyclic graph)，它编码了完整的计算历史。

每个张量都有一个.grad_fn属性，该属性引用了创建 Tensor自身的Function(除非这个张量是用户手动创建的，即这个张量的grad_fn是 None )。

如果需要计算导数，可以在 Tensor 上调用 .backward()。如果Tensor 是一个标量(即它包含一个元素的数据），则不需要为 backward()指定任何参数，但是如果它有更多的元素，则需要指定一个gradient参数，该参数是形状匹配的张量。

In [20]:
import torch

**创建一个张量并设置requires_grad=True用来追踪其计算历史**

In [21]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [22]:
y = x**2
print(y)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)


In [23]:
y

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)

**y是计算的结果，所以它有grad_fn属性。**

In [24]:
print(y.grad_fn)

In [25]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>) tensor(3., grad_fn=<MeanBackward0>)


In [38]:
z.mean(dim=0, keepdim=False).shape

torch.Size([2])

In [43]:
z.mean(dim=0, keepdim=True).shape

torch.Size([1, 2])

In [42]:
z.mean(dim=1, keepdim=False)

tensor([3., 3.], grad_fn=<MeanBackward1>)

.requires_grad_(...)原地改变了现有张量的requires_grad标志。如果没有指定的话，默认输入的这个标志是False。

In [44]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)

False


In [45]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [46]:
b = (a*a).sum()
print(b.grad_fn)

**梯度**

现在开始进行反向传播，因为out 是一个标量，因此out.backward()和out.backward(torch.tensor(1.)) 等价。

In [47]:
out.backward()

In [48]:
print(x.grad)

tensor([[3., 3.],
        [3., 3.]])


**注意：grad在反向传播过程中是累加的(accumulated)，这意味着每一次运行反向传播，梯度都会累加之前的梯度，所以一般在反向传播之前需把梯度清零。**

In [50]:
out2 = x.sum()

In [53]:
out2

tensor(4., grad_fn=<SumBackward0>)

In [52]:
# 再来反向传播⼀一次，注意grad是累加的 2 out2 = x.sum()
out2.backward()
print(x.grad)

tensor([[5., 5.],
        [5., 5.]])


In [55]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [56]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()

In [57]:
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [71]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
i = 0
while y.data.norm() < 1000:
    y = y * 2
    i = i + 1
print(y)
print(i)

tensor([-0.0645, -1.4783,  0.6735], requires_grad=True)
tensor([  -66.0058, -1513.7406,   689.6312], grad_fn=<MulBackward0>)
9


**在这种情况下，y不再是标量。torch.autograd 不能直接计算完整的雅可比矩阵，但是如果我们只想要雅可比向量积，只需将这个向量作为参数传给 backward：**

In [68]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

In [69]:
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [65]:
x.grad.data.zero_()

tensor([0., 0., 0.])

**在使用.grad.data.zero_()方法以后，y 是依赖 x 生成的，所以需要重新 计算一次 y，x 才会有梯度。**

In [72]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [ ]:
"""
在向量微积分中，雅可比矩阵是一阶偏导数以一定方式排列成的矩阵，其行列式称为雅可比行列式。
雅可比矩阵的重要性在于它体现了一个可微方程与给出点的最优线性逼近。
因此，雅可比矩阵类似于多元函数的导数。 
"""

也可以通过将代码块包装在with torch.no_grad(): 中，来阻止 autograd 跟踪设置了.requires_grad=True的张量的历史记录。

In [73]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [74]:
with torch.no_grad():
    print((x**2).requires_grad)

False


如果我们想要修改 tensor 的数值，但是又不希望被 autograd 记录(即不会影响反向传播)， 那么我么可以对 tensor.data 进行操作。

In [75]:
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值 
print(x.grad)


tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])


In [76]:
x = torch.ones(1,requires_grad=True)
y = 2 * x
y.backward()
print(x.grad)

tensor([2.])


In [80]:
x = torch.ones(1,requires_grad=True)
y = 2 * x
x.data *= 100
y.backward()
print(x.grad)

tensor([2.])


#### 并行计算简介

在利用PyTorch做深度学习的过程中，可能会遇到数据量较大无法在单块GPU上完成，或者需要提升计算速度的场景，这时就需要用到并行计算。

我暂时还没遇到过。。还是太菜了

CUDA是我们使用GPU的提供商——NVIDIA提供的GPU并行计算框架。对于GPU本身的编程，使用的是CUDA语言来实现的。但是，在我们使用PyTorch编写深度学习代码时，使用的CUDA又是另一个意思。在PyTorch使用 CUDA表示要开始要求我们的模型或者数据开始使用GPU了。

**在编写程序中，当我们使用了 cuda() 时，其功能是让我们的模型或者数据迁移到GPU当中，通过GPU开始计算。**

**不同的数据分布到不同的设备中，执行相同的任务(Data parallelism)**

第三种方式有点不一样，它的逻辑是，我不再拆分模型，我训练的时候模型都是一整个模型。但是我将输入的数据拆分。所谓的拆分数据就是，同一个模型在不同GPU中训练一部分数据，然后再分别计算一部分数据之后，只需要将输出的数据做一个汇总，然后再反传。其架构如下：

**PS:现在的主流方式是数据并行的方式(Data parallelism)**